### ISSUE TITLE
Laravel 5.6 installation

### ISSUE THREAD

**Issue by uapixart** [vimeo/laravel#27]
Good day!
When make upgrade upgrade or instalation on Laravel 5.6:

$ /usr/local/bin/composer require vimeo/laravel
Using version ^4.0 for vimeo/laravel
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for vimeo/laravel ^4.0 -> satisfiable by vimeo/laravel[4.0.0].
    - Conclusion: remove laravel/framework v5.6.3
    - Conclusion: don't install laravel/framework v5.6.3
    - vimeo/laravel 4.0.0 requires illuminate/contracts 5.5.* -> satisfiable by illuminate/contracts[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34].
    - don't install illuminate/contracts v5.5.0|don't install laravel/framework v5.6.3
    - don't install illuminate/contracts v5.5.16|don't install laravel/framework v5.6.3
    - don't install illuminate/contracts v5.5.17|don't install laravel/framework v5.6.3
    - don't install illuminate/contracts v5.5.2|don't install laravel/framework v5.6.3
    - don't install illuminate/contracts v5.5.28|don't install laravel/framework v5.6.3
    - don't install illuminate/contracts v5.5.33|don't install laravel/framework v5.6.3
    - don't install illuminate/contracts v5.5.34|don't install laravel/framework v5.6.3
    - Installation request for laravel/framework (locked at v5.6.3, required as 5.6.*) -> satisfiable by laravel/framework[v5.6.3].

Installation failed, reverting ./composer.json to its original content.

**Comment by slakbal** [comment]
@vinkla yeah would be awesome if the package could be upgraded to support Laravel 5.6 since we are currently updating our project which uses this package.

**Comment by vinkla** [comment]
@slakbal you're free to submit a pull request to add Laravel 5.6 support. 

If you want to, [you can use this pull request as a reference](https://github.com/vinkla/laravel-hashids/commit/b289c500c04750fd4086aa89099e360975299e9e).

**Comment by erunion** [comment]
5.0.0 release has this now. Thanks!

**Comment by bryanJC1101** [comment]
@vinkla i cannot install laravel/vimeo on laravel 5.7

**Comment by erunion** [comment]
@bryanJC1101 Laravel 5.7 is was targeted on the 4.0.0 release. Try that instead.

// @onebrownsound
