### ISSUE TITLE
Can't install this for Laravel 5.5

### ISSUE THREAD

**Issue by hassanazimi** [vimeo/laravel#30]
```
 Problem 1
    - Installation request for vimeo/laravel ^5.0 -> satisfiable by vimeo/laravel[5.0.0].
    - Conclusion: remove laravel/framework v5.5.35
    - Conclusion: don't install laravel/framework v5.5.35
    - vimeo/laravel 5.0.0 requires illuminate/contracts 5.6.* -> satisfiable by illuminate/contracts[v5.6.0, v5.6.1, v5.6.2, v5.6.3, v5.6.4, v5.6.5].
    - don't install illuminate/contracts v5.6.0|don't install laravel/framework v5.5.35
    - don't install illuminate/contracts v5.6.1|don't install laravel/framework v5.5.35
    - don't install illuminate/contracts v5.6.2|don't install laravel/framework v5.5.35
    - don't install illuminate/contracts v5.6.3|don't install laravel/framework v5.5.35
    - don't install illuminate/contracts v5.6.4|don't install laravel/framework v5.5.35
    - don't install illuminate/contracts v5.6.5|don't install laravel/framework v5.5.35
    - Installation request for laravel/framework (locked at v5.5.35, required as 5.5.*) -> satisfiable by laravel/framework[v5.5.35].
```

Do your package really needs Eloquent 5.6.* ?

**Comment by erunion** [comment]
This package doesn't require Eloquent.

If you want to install it on Laravel 5.5, install the [4.0 version](https://packagist.org/packages/vimeo/laravel#4.0.0).

```
composer require vimeo/laravel ^4.0
```

**Comment by hassanazimi** [comment]
there is not version 4.0 version before this version was renamed.

**Comment by erunion** [comment]
When we renamed the package, we tagged 4.0 shortly after. 

I was able to install 4.0 just now.

```
$ composer require vimeo/laravel ^4.0
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 11 installs, 0 updates, 0 removals
  - Installing vimeo/vimeo-api (2.0.0): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.7.0): Loading from cache
  - Installing symfony/translation (v3.4.4): Loading from cache
  - Installing nesbot/carbon (1.22.1): Downloading (100%)         
  - Installing psr/simple-cache (1.0.0): Loading from cache
  - Installing psr/container (1.0.0): Loading from cache
  - Installing illuminate/contracts (v5.5.35): Loading from cache
  - Installing doctrine/inflector (v1.3.0): Loading from cache
  - Installing illuminate/support (v5.5.35): Downloading (100%)         
  - Installing graham-campbell/manager (v3.0.0): Loading from cache
  - Installing vimeo/laravel (4.0.0): Loading from cache
symfony/translation suggests installing symfony/config ()
symfony/translation suggests installing symfony/yaml ()
symfony/translation suggests installing psr/log (To use logging capability in translator)
illuminate/support suggests installing illuminate/filesystem (Required to use the composer class (5.2.*).)
illuminate/support suggests installing symfony/process (Required to use the composer class (~3.3).)
illuminate/support suggests installing symfony/var-dumper (Required to use the dd function (~3.3).)
Writing lock file
Generating autoload files
```

**Comment by bryanJC1101** [comment]
Problem 1                                                                                                                                                                                                                                                                         - Conclusion: remove laravel/framework v5.7.26                                                                                                                                                                                                                                  - Conclusion: don't install laravel/framework v5.7.26                                                                                                                                                                                                                           - vimeo/laravel 5.3.0 requires illuminate/support ^5.8 -> satisfiable by laravel/framework[5.8.x-dev, 5.9.x-dev], illuminate/support[5.8.x-dev, 5.9.x-dev, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.3, v5.8.4,  v5.8.8, v5.8.9].                                                                                                                                                                                                                                                                   - vimeo/laravel 5.3.1 requires illuminate/support ^5.8 -> satisfiable by laravel/framework[5.8.x-dev, 5.9.x-dev], illuminate/support[5.8.x-dev, 5.9.x-dev, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.3, v5.8.4,  v5.8.8, v5.8.9].                                                                                                                                                                                                                                                                   - vimeo/laravel 5.3.2 requires illuminate/support ^5.8 -> satisfiable by laravel/framework[5.8.x-dev, 5.9.x-dev], illuminate/support[5.8.x-dev, 5.9.x-dev, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.3, v5.8.4,  v5.8.8, v5.8.9].                                                                                                                                                                                                                                                                   - Can only install one of: laravel/framework[5.8.x-dev, v5.7.26].                                                                                                                                                                                                               - Can only install one of: laravel/framework[5.9.x-dev, v5.7.26].                                                                                                                                                                                                               - don't install illuminate/support 5.8.x-dev\|don't install laravel/framework v5.7.26                                                                                                                                                                                            - don't install illuminate/support v5.8.0\|don't install laravel/framework v5.7.26                                                                                                                                                                                               - don't install illuminate/support v5.8.11\|don't install laravel/framework v5.7.26                                                                                                                                                                                              - don't install illuminate/support v5.8.12\|don't install laravel/framework v5.7.26                                                                                                                                                                                              - don't install illuminate/support v5.8.14\|don't install laravel/framework v5.7.26                                                                                                                                                                                              - don't install illuminate/support v5.8.15\|don't install laravel/framework v5.7.26                                                                                                                                                                                              - don't install illuminate/support v5.8.17\|don't install laravel/framework v5.7.26                                                                                                                                                                                              - don't install illuminate/support v5.8.18\|don't install laravel/framework v5.7.26                                                                                                                                                                                              - don't install illuminate/support v5.8.19\|don't install laravel/framework v5.7.26                                                                                                                                                                                              - don't install illuminate/support v5.8.2\|don't install laravel/framework v5.7.26                                                                                                                                                                                               - don't install illuminate/support v5.8.20\|don't install laravel/framework v5.7.26                                                                                                                                                                                              - don't install illuminate/support v5.8.22\|don't install laravel/framework v5.7.26                                                                                                                                                                                              - don't install illuminate/support v5.8.3\|don't install laravel/framework v5.7.26                                                                                                                                                                                               - don't install illuminate/support v5.8.4\|don't install laravel/framework v5.7.26                                                                                                                                                                                               - don't install illuminate/support v5.8.8\|don't install laravel/framework v5.7.26                                                                                                                                                                                               - don't install illuminate/support v5.8.9\|don't install laravel/framework v5.7.26                                                                                                                                                                                               - don't install illuminate/support 5.9.x-dev\|don't install laravel/framework v5.7.26                                                                                                                                                                                            - Installation request for laravel/framework (locked at v5.7.26, required as 5.7.*) -> satisfiable by laravel/framework[v5.7.26].                                                                                                                                               - Installation request for vimeo/laravel ^5.3 -> satisfiable by vimeo/laravel[5.3.0, 5.3.1, 5.3.2].
--

**Comment by erunion** [comment]
// @onebrownsound
