### ISSUE TITLE
You must provide a valid authenticated access token

### ISSUE THREAD

**Issue by 1quintana** [vimeo/laravel#32]
I saw that someone else already reported this issue and even when your answer was not very friendly to him I was wondering if you already figure it out?

I am wondering if this is related to the domain that I register when I registered the app, but I am confuse because they say that you can enter anyone if you are in develop environment.
   
<pre>
 'connections' => [

        'main' => [
            'client_id' =>  env('VIMEO_CLIENT_ID'),
            'client_secret' => env('VIMEO_CLIENT_SECRET'),
            'access_token' => null,
        ],

        'alternative' => [
            'client_id' => 'your-client-id',
            'client_secret' => 'your-client-secret',
            'access_token' => null,
        ],

    ],

</pre>

**Comment by vinkla** [comment]
> …even when your answer was not very friendly to him…

I'm guessing you're referring to [this issue](https://github.com/vimeo/laravel/issues/15). Please note that this is open source software which was built for you to use **for free**. This is not a hotline for support questions.

**Comment by erunion** [comment]
@1quintana Certain endpoints of the Vimeo API require a valid access token, which you need to generate through the [authentication process](https://github.com/vimeo/vimeo.php#generate-your-access-token).

**Comment by 1quintana** [comment]
@erunion thank you for your answer, but if you read my message I said the problem could be related to the domain that I register when I registered the app with them which will provide the access token and they are already in my .env file if you check the provided code. Vimeo take for ever to reply they are rely bad on that so we decided to move on with youtube.
