### ISSUE TITLE
upload video

### ISSUE THREAD

**Issue by icyz** [vimeo/laravel#34]
I've tried to upload video without success using this code:
 `    $video = public_path('Wildog.mp4');`
 `    $u = Vimeo::upload($video);`

My laravel version is 5.6, installed with composer.
Php 7.1.14

I can't figured out, I have no error and in my vimeo account the video is created (empty).
The page seems "loading" but no one single byte is transferred to vimeo.

**Comment by erunion** [comment]
Closing this out in favor of https://github.com/vimeo/vimeo.php/issues/167
