### ISSUE TITLE
Add support for Laravel 5.6

### ISSUE THREAD

**Issue by petersontubini** [vimeo/laravel#35]
- vinkla/vimeo 3.7.0 requires illuminate/support 5.5.* -> satisfiable by illuminate/support[5.5.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40].

**Comment by erunion** [comment]
We have Laravel 5.6 support in 5.0, so upgrading your dependency from 3.7.0 to that should resolve this.

```
composer require vimeo/laravel ^5.0
```
