### ISSUE TITLE
Parameters (title, description, etc...)

### ISSUE THREAD

**Issue by rkg0612** [vimeo/laravel#36]
Hi,

I've already dissected your package and have not found a single code to upload a video with title and description. Do I miss something?

**Comment by erunion** [comment]
Hi @rkg0612, this library is just a wrapper for our PHP SDK: https://github.com/vimeo/vimeo.php

You can see documentation for uploading a video with a title and description with it here: https://github.com/vimeo/vimeo.php#uploading-videos

So you'd do something like:

```php
$response = Vimeo::upload('/bar.mp4', [
     'name' => 'video title',
     'description' => 'video description'
]);
```
