### ISSUE TITLE
Version Issue Workaround for "invalid_bucket"

### ISSUE THREAD

**Issue by mstaack** [vimeo/laravel#68]
Currently installation is broken due to the peer dependency `tus @ v0.1.0` which hard requires carbon v1 as seen here: https://packagist.org/packages/ankitpokhrel/tus-php#v0.1.0

![image](https://user-images.githubusercontent.com/10169509/68942413-d785ed00-07a8-11ea-8334-26ae54525ebf.png)
![image](https://user-images.githubusercontent.com/10169509/68942435-e40a4580-07a8-11ea-9380-79c03d0369ec.png)

aliasing carbon before you require the laravel package with:
```bash
composer require "nesbot/carbon:2.26 as 1.25.0"
``` 
solves this issue for now. **but should be fixed on package side.**

after that a fresh install of the package gives the correct `3.0.2` version:

```bash
composer require "vimeo/laravel"
Using version ^5.4 for vimeo/laravel
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 4 installs, 0 updates, 0 removals
  - Installing ankitpokhrel/tus-php (v0.1.0): Loading from cache
  - Installing vimeo/vimeo-api (3.0.2): Loading from cache
  - Installing graham-campbell/manager (v4.3.0): Loading from cache
  - Installing vimeo/laravel (5.4.1): Loading from cache
```
solving all kinds of issues related to `invalid_bucket`

**Comment by tommypenner** [comment]
@mstaack Thanks for the writeup! We have a PR in review now that should resolve this issue.

**Comment by mstaack** [comment]
works correctly with latest packages..
