### ISSUE TITLE
Laravel 7.0 support

### ISSUE THREAD

**Issue by paul-a-byford** [vimeo/laravel#71]
Can this package be used with laravel 7.0? The package works fine on laravel 6.0.

When attempted to install this package on laravel 7.0 I get an error message similar to this existing issue https://github.com/vimeo/laravel/issues/59

**Comment by mstaack** [comment]
master branch already contains 7.0 references:
https://github.com/vimeo/laravel/blob/master/composer.json

just missing a proper release/tag

**Comment by muglug** [comment]
I’ve just released
