### ISSUE TITLE
No user credentials were provided 

### ISSUE THREAD

**Issue by ikramooe** [vimeo/laravel#76]
Hello , 
so when i try to upload a video to my Vimeo  i get the error no user credentials were provided 
even though i did set them here 
'main' => [
            'client_id' => env('VIMEO_CLIENT', 'MY CODE'),
            'client_secret' => env('VIMEO_SECRET', 'MY CODE '),
            'access_token' => env('VIMEO_ACCESS', 'MY CODE '),
        ],

**Comment by abhinay1435** [comment]
You need to Generate a Access Token from Vimeo with all the access like below

Go to My Apps Page
https://developer.vimeo.com/apps
Choose Your App
Then on the left hand Menu Click Permissions and then

![image](https://user-images.githubusercontent.com/7387189/204503786-cf91d42c-e31b-4d07-b05d-8311a0894a6e.png)
Generate a New Token and then use that
