### ISSUE TITLE
Hash parameter

### ISSUE THREAD

**Issue by glacier890** [vimeo/laravel#95]
Vimeo made some changes last year that if you have your videos as unlisted then you need to include the hash parameter to be able to embed the videos on your site. Is there a way to include the hash parameter in the response of the upload method?

**Comment by aaronm67** [comment]
Yes - when you request a video, you can use:

`/videos/{video_id}:{video_hash}`

So, `Vimeo::request('/videos/1234:abcd')`

**Comment by glacier890** [comment]
Thank you for the response. Sorry if I am misunderstanding your reply, but my issue is when I use the upload method to upload the video to Vimeo, I need to get the hash parameter in the response so I can store the hash parameter to our database. It seems like the only way to find the hash parameter for each video is logging in to Vimeo and finding it manually.

**Comment by glacier890** [comment]
That worked perfectly. Thank you!
